In [50]:
import numpy as np
import pandas as pd
import seaborn as sns
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [51]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [52]:
df=pd.read_csv('/content/top_100_nepali_movies.csv')

In [53]:
df.isnull().sum()

Title          0
Description    0
Tags           0
dtype: int64

In [54]:
stop_words=set(nltk.corpus.stopwords.words('nepali'))
leammatizer=WordNetLemmatizer()

In [55]:
df

,Title,Description,Tags
0,पूर्ण बहादुरको सारङ्गी,बाबु-छोराको भावनात्मक सम्बन्ध र समाजको कठोरताल...,"सामाजिक, नाटक, परिवार, संघर्ष, सारङ्गी"
1,कबड्डी,मुस्ताङको काजी र मैयाँको प्रेम कथा तथा गाउँले ...,"हास्य, सामाजिक, प्रेम कथा, संस्कृति, मुस्ताङ"
2,लुट,काठमाडौँमा बैंक डकैतीको योजना बुन्ने पाँच युवा...,"अपराध, थ्रिलर, एक्सन, काठमाडौँ, डकैती"
3,पशुपति प्रसाद,ऋण तिर्न काठमाडौँ आएको सोझो युवकको संघर्ष र पश...,"सामाजिक, नाटक, संघर्ष, पशुपति, जीवन"
4,दर्पण छायाँ,दुई साथीहरूको प्रगाढ मित्रता र एउटी युवतीप्रति...,"प्रेम कथा, मित्रता, संगीतमय, विछोड, क्लासिक"
...,...,...,...
95,परदेशी २,वैदेशिक रोजगारीका लागि खाडी मुलुक जाने युवाको ...,"वैदेशिक रोजगारी, खाडी, भावुक, सामाजिक, परिवार"
96,उन्को स्विटर,पूर्वी नेपालको गाउँमा स्विटर बुन्ने कथा र प्रेम।,"रोमान्स, पूर्वी नेपाल, गाउँ, संस्कृति, ड्रामा"
97,परान,पारिवारिक सम्बन्ध र गाउँले जीवनको भावनात्मक आयाम।,"पारिवारिक, सामाजिक, गाउँ, भावुक, ड्रामा"
98,गौथली,नेपाली लोक जीवन र गौथलीसँग जोडिएको कथा।,"लोक संस्कृति, सामाजिक, गाउँ, ड्रामा"
99,आ बाट आमा,आमाको ममता र मातृभूमिको महत्त्व दर्साउने कथा।,"आमा, देशप्रेम, पारिवारिक, भावुक, सामाजिक"

In [56]:
df['combined']=(df['Title'])*2 +' '+ df['Description']+' '+df['Tags']

In [57]:
df

,Title,Description,Tags,combined
0,पूर्ण बहादुरको सारङ्गी,बाबु-छोराको भावनात्मक सम्बन्ध र समाजको कठोरताल...,"सामाजिक, नाटक, परिवार, संघर्ष, सारङ्गी",पूर्ण बहादुरको सारङ्गीपूर्ण बहादुरको सारङ्गी ब...
1,कबड्डी,मुस्ताङको काजी र मैयाँको प्रेम कथा तथा गाउँले ...,"हास्य, सामाजिक, प्रेम कथा, संस्कृति, मुस्ताङ",कबड्डीकबड्डी मुस्ताङको काजी र मैयाँको प्रेम कथ...
2,लुट,काठमाडौँमा बैंक डकैतीको योजना बुन्ने पाँच युवा...,"अपराध, थ्रिलर, एक्सन, काठमाडौँ, डकैती",लुटलुट काठमाडौँमा बैंक डकैतीको योजना बुन्ने पा...
3,पशुपति प्रसाद,ऋण तिर्न काठमाडौँ आएको सोझो युवकको संघर्ष र पश...,"सामाजिक, नाटक, संघर्ष, पशुपति, जीवन",पशुपति प्रसादपशुपति प्रसाद ऋण तिर्न काठमाडौँ आ...
4,दर्पण छायाँ,दुई साथीहरूको प्रगाढ मित्रता र एउटी युवतीप्रति...,"प्रेम कथा, मित्रता, संगीतमय, विछोड, क्लासिक",दर्पण छायाँदर्पण छायाँ दुई साथीहरूको प्रगाढ मि...
...,...,...,...,...
95,परदेशी २,वैदेशिक रोजगारीका लागि खाडी मुलुक जाने युवाको ...,"वैदेशिक रोजगारी, खाडी, भावुक, सामाजिक, परिवार",परदेशी २परदेशी २ वैदेशिक रोजगारीका लागि खाडी म...
96,उन्को स्विटर,पूर्वी नेपालको गाउँमा स्विटर बुन्ने कथा र प्रेम।,"रोमान्स, पूर्वी नेपाल, गाउँ, संस्कृति, ड्रामा",उन्को स्विटरउन्को स्विटर पूर्वी नेपालको गाउँमा...
97,परान,पारिवारिक सम्बन्ध र गाउँले जीवनको भावनात्मक आयाम।,"पारिवारिक, सामाजिक, गाउँ, भावुक, ड्रामा",परानपरान पारिवारिक सम्बन्ध र गाउँले जीवनको भाव...
98,गौथली,नेपाली लोक जीवन र गौथलीसँग जोडिएको कथा।,"लोक संस्कृति, सामाजिक, गाउँ, ड्रामा",गौथलीगौथली नेपाली लोक जीवन र गौथलीसँग जोडिएको ...
99,आ बाट आमा,आमाको ममता र मातृभूमिको महत्त्व दर्साउने कथा।,"आमा, देशप्रेम, पारिवारिक, भावुक, सामाजिक",आ बाट आमाआ बाट आमा आमाको ममता र मातृभूमिको महत...

In [58]:
def preprocessing_nepali(text):
  cleaned_text = re.sub(r'[^\u0900-\u097F\s]', '', text)

  cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
  words=cleaned_text.split()
  words=[word for word in words if word not in stop_words]
  words=[leammatizer.lemmatize(word) for word in words]
  return ' '.join(words)

In [59]:
df['combined']=df['combined'].apply( preprocessing_nepali)

In [60]:
indices = pd.Series(df.index, index=df['Title']).drop_duplicates()

In [61]:
indices

Title
पूर्ण बहादुरको सारङ्गी     0
कबड्डी                     1
लुट                        2
पशुपति प्रसाद              3
दर्पण छायाँ                4
                          ..
परदेशी २                  95
उन्को स्विटर              96
परान                      97
गौथली                     98
आ बाट आमा                 99
Length: 100, dtype: int64

VECTORIZATION

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
tfidf=TfidfVectorizer(max_features=300,ngram_range=(1,2))

In [64]:
tfidf_matrix=tfidf.fit_transform(df['combined'])

In [72]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 941 stored elements and shape (100, 300)>

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
def recommend(Title,n=5):
  if Title not in indices:
    return ['Movie not Found']
  idx=indices[Title]
  sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  sim_id=sim_score.argsort()[::-1][1:n+1]
  return df['Title'].iloc[sim_id]

In [71]:
recommend('छक्का पञ्जा')

23    छक्का पञ्जा ५
20    छक्का पञ्जा २
22    छक्का पञ्जा ४
21    छक्का पञ्जा ३
95         परदेशी २
Name: Title, dtype: object